services:
#   mysql:
#     image: mysql:8.0
#     ports:
#       - 3306:3306

#     environment:
    
#       - MYSQL_DATABASE=poolhub
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


#     volumes:

#       - poolhubdata:/var/lib/mysql 


  redis:
    image: redis
    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 5

  django:

    build: .
    command: ["gunicorn", "poolhub.wsgi:application", "-b", "0.0.0.0:8000", '--reload']
    # ./wait-for-it.sh", "mysql:3306", "--",

    # ports:
    #   - "8000:8000"

    volumes:
      - .:/app

    environment:
      - DB_HOST=mysql
      - DB_PASSWORD=${DB_PASSWORD}
      - REMOTE_DB_HOST=${ REMOTE_DB_HOST}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}



    depends_on:
      # - mysql
      - redis
      - celery

    restart: on-failure

  celery:
    build: .
    command: celery -A poolhub worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      
      

  # celery-beat:
  #   build: .
  #   command: celery -A poolhub beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
      
  #     redis:
  #       condition: service_healthy



  daphne:
    build: .
    command: ["daphne", "-u", "/tmp/daphne.sock", "--application-close-timeout", "10", "poolhub.asgi:application"]
    # "--bind", "0.0.0.0", "--port", "8001"
    # ports:
    #   - "8001:8001"
    volumes:
      - .:/app
      - daphne-socket:/tmp
    environment:
      - DB_HOST=mysql

      - REMOTE_DB_HOST=${REMOTE_DB_HOST}
      - REMOTE_DB_NAME=${REMOTE_DB_NAME}
      - REMOTE_DB_USER=${REMOTE_DB_USER}
      - REMOTE_DB_PORT=${REMOTE_DB_PORT}
      - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      # - mysql
      - redis


  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
      # - "443:443" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/static
      - ./media:/app/media
      - daphne-socket:/tmp
    depends_on:
      - django
      - daphne
    restart: always

volumes:
  daphne-socket:
  # poolhubdata: