

services:
  postgres:
    image: postgres:16.3
    
    environment:
      - POSTGRES_DB=${P_DB_NAME}
      - POSTGRES_USER=${P_DB_USER}
      - POSTGRES_PASSWORD=${P_DB_PASSWORD}


    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


  redis:
    image: redis
    ports:
      - "6739:6739"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 5

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      - DB_HOST=postgres

    depends_on:
      - postgres
      - redis
      - celery

  celery:
    build: .
    command: celery -A poolhub worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      
      

  # celery-beat:
  #   build: .
  #   command: celery -A poolhub beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
      
  #     redis:
  #       condition: service_healthy



