services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
    
      - MYSQL_DATABASE=poolhub
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


    volumes:

      - ../mysqldata:/var/lib/mysql 


  redis:
    image: redis
    ports:
      - "6739:6739"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 5

  django:

    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}



    depends_on:
      - mysql
      - redis
      - celery

    restart: on-failure

  celery:
    build: .
    command: celery -A poolhub worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      
      

  # celery-beat:
  #   build: .
  #   command: celery -A poolhub beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
      
  #     redis:
  #       condition: service_healthy



